import { Figtree } from "next/font/google";

import CopyrightFooter from "@/components/CopyrightFooter";

import "./globals.css";

const figTree = Figtree({
  variable: "--font-figtree",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${figTree.variable} antialiased`}>
        {children}
        <CopyrightFooter
          text={`© ${new Date().getFullYear()} All rights reserved.`}
          links={[
            { label: "Privacy Policy", href: "/privacy-policy" },
            { label: "Terms & Conditions", href: "/terms" },
            { label: "Cookie Policy", href: "/cookie-policy" },
          ]}
        />
      </body>
    </html>
  );
}
